AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Sample Template for creating a Multi-AZ DB cluster.

Parameters:
  DBInitialname:
    Description: Database Initial name
    Type: String
    Default: customer_info

  NetWorkStack:
    Type: String
    Description: NetworkStack
    Default: networkStack #exported stack name

  DBUsername:
    NoEcho: 'false'
    Description: Username for database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.

  DBPassword:
    NoEcho: 'true'
    Description: Password for database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alphanumeric characters.

  DBClusterIdentifier:
    Type: String
    Default: "nas-db-cluster"

  Engine:
    Type: String
    Default: aurora-mysql

  EngineVersion:
    Type: String
    Default: "5.7.mysql_aurora.2.10.2"

  # AllocatedStorage:
  #   Type: Number
  #   Default: "400"

  # Iops:
  #   Type: Number
  #   Default: "3000"
  
  # DBInstanceType:
  #   Description: Database Instance Class
  #   Type: String
  #   Default: db.r6g.2xlarge
  #   AllowedValues:
  #     - db.t2.xlarge
  #     - db.r6g.2xlarge
  #     - db.t3.small
  #     - db.t3.medium
  #     - db.t3.large
  #     - db.t4g.large
  #     - db.m6gd.xlarge

Resources:
  NasMultiAZDBCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBClusterIdentifier: !Ref DBClusterIdentifier
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      # AllocatedStorage: !Ref AllocatedStorage
      # Iops: !Ref Iops
      # DBClusterInstanceClass: !Ref DBInstanceType
      BackupRetentionPeriod: 1
      # StorageType: io1
      Port: 3306
      DBSubnetGroupName: !Ref NasSubnetGroup
      DBClusterParameterGroupName: default.aurora-mysql5.7
      # AvailabilityZones:
      #   - us-west-2a
      #   - us-west-2b
      #   - us-west-2c


  NasSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: NAS Subnet Group
      DBSubnetGroupName: nassubnets
      SubnetIds: 
        - Fn::ImportValue:
            Fn::Sub: ${NetWorkStack}-PrivateSubnetOneId
        - Fn::ImportValue:
            Fn::Sub: ${NetWorkStack}-PrivateSubnetTwoId
        - Fn::ImportValue:
            Fn::Sub: ${NetWorkStack}-PrivateSubnetThreeId